---
# W. Cyrus Proctor
# Virtual Slurm Cluster
# 2019-02-02

- hosts: all
  roles:
    - { role: common, tags: common }
    - { role: slurm_common, tags: slurm_common }

- hosts: s
  roles:
    - { role: slurm_server, tags: slurm_server }

- hosts: c
  roles:
    - { role: slurm_compute, tags: slurm_compute }

- hosts: l
  roles:
    - { role: slurm_login, tags: slurm_login }
